version: '3.4'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports: 
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: yourStrong____Password
  
  react-admin:
    image: pqx.react.admin
    ports: 
      - 80:44486
      - 443:44300
    build: app/DotNetCoreReactAdmin-dotnet7
    depends_on: 
        - mssql   